version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ubuntu-server:22.04
    environment:
      - CACHE_DIR: ~/build/wxWidgets/staticlib
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ checksum "travis-ci/build_wxwidgets.sh" }}
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libpulse-dev libgtk-3-dev freeglut3 freeglut3-dev libhamlib-dev
      - run:
          name: Build LiquidDSP
          command: bash travis-ci/build_liquiddsp.sh
      - run:
          name: Build SoapySDR
          command: bash travis-ci/build_soapysdr.sh
      - run:
          name: Build wxWidgets
          command: bash travis-ci/build_wxwidgets.sh
      - run:
          name: Build CubicSDR
          command: bash travis-ci/build_cubicsdr.sh
      - save_cache:
          key: cache-{{ checksum "travis-ci/build_wxwidgets.sh" }}
          paths:
            - ~/build/wxWidgets/staticlib
